# Generated by Django 5.0.1 on 2024-02-06 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_vid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vid Users',
                'verbose_name_plural': 'Vid Users',
            },
        ),
        migrations.CreateModel(
            name='SendMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(related_name='admin_message', to='vidcompressbot.uservid')),
            ],
            options={
                'verbose_name': 'Vid SendMessage',
                'verbose_name_plural': 'Vid SendMessage',
            },
        ),
        migrations.CreateModel(
            name='VidPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('day', models.IntegerField()),
                ('volum', models.IntegerField()),
                ('des', models.TextField()),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.botmodel')),
            ],
            options={
                'verbose_name': 'Vid Plans',
                'verbose_name_plural': 'Vid Plans',
            },
        ),
        migrations.CreateModel(
            name='SubVidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('volum', models.IntegerField(blank=True, default=0, null=True)),
                ('volum_used', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.botmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='vidcompressbot.uservid')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vidcompressbot.vidplanmodel')),
            ],
            options={
                'verbose_name': 'Vid User Subscription',
                'verbose_name_plural': 'Vid User Subscription',
            },
        ),
        migrations.CreateModel(
            name='VidSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='bot status')),
                ('not_active_text', models.TextField(default='خالی', verbose_name='bot text off')),
                ('admin_chat_id', models.IntegerField(verbose_name='chat_id admin')),
                ('support_id', models.CharField(default='خالی', max_length=128)),
                ('support_text', models.TextField(default='خالی')),
                ('help_text', models.TextField(default='خالی')),
                ('video_compressor_status', models.BooleanField(default=True)),
                ('video_compressor_text', models.TextField(default='خالی')),
                ('start_text', models.TextField(default='خالی')),
                ('restrict_saving_content', models.BooleanField(default=False)),
                ('actication_sub_tex', models.TextField(default='خالی')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.botmodel', verbose_name='telegram bot')),
            ],
            options={
                'verbose_name': 'Vid Setting',
                'verbose_name_plural': 'Vid Setting',
            },
        ),
    ]
