# Generated by Django 5.0.1 on 2024-02-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidcompressbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessagemodel',
            name='user',
            field=models.ManyToManyField(related_name='admin_message', to='vidcompressbot.uservid'),
        ),
    ]
