# Generated by Django 5.0.1 on 2024-02-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('api_hash', models.CharField(max_length=225)),
                ('api_id', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'My Bots',
                'verbose_name_plural': 'My Bots',
            },
        ),
        migrations.CreateModel(
            name='BotSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('val', models.CharField(blank=True, max_length=200, null=True)),
                ('setting', models.JSONField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='core.botmodel')),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Setting',
            },
        ),
    ]
