# Generated by Django 5.0.1 on 2024-02-03 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('token', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('val', models.CharField(blank=True, max_length=200, null=True)),
                ('setting', models.JSONField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='core.botmodel')),
            ],
        ),
    ]
