# Generated by Django 5.0.1 on 2024-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('token', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
